---
title: "Kayin evergreen tropical rainforest"
---



https://www.myanmar-ecosystems.org/

https://www.myanmar-ecosystems.org/myanmar-ecosystems/t1-1-5-kayin-evergreen-tropical-rainforest

Description

This very diverse, closed-canopy, non-sundaic rainforest comprises a diverse suite of trees including prominent Dipterocarpaceae, but few emergents. Buttressed trees are common, epiphytes, ferns and lianas are abundant. Canes, palms and bamboos are present in the understorey, and become abundant in areas of high disturbance. This ecosystem has a more seasonal climate, and a less diverse biota than upland and lowland rainforests further south in Tanintharyi. Nevertheless, it supports a diverse fauna community with birds, bats and insects being important pollinators in the canopy.

Assessment summary 

This ecosystem is restricted to southeast Myanmar, and there is evidence of ongoing declines due to rubber plantation development, logging, and cutting timber for shifting cultivation. A climate simulation model does not suggest major reductions in environmental suitability and the Forest Landscape Integrity Index suggests remaining patches are relatively intact. Primary forest data suggest that more than 77% of this ecosystem has been degraded since 1750, meeting category thresholds for Endangered under Criterion D3. Endangered.

