theme: jekyll-theme-cayman
title: "IUCN RLE bibliography"

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "listas"
    values:
      layout: "listas"
  - scope:
      path: ""
    values:
      layout: "default"
