theme: jekyll-theme-cayman
title: "IUCN RLE bibliography"

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
 - scope:
      path: ""
    values:
      layout: "default"
 
